// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Health() {
  return window['go']['main']['DesktopApp']['Health']();
}

export function ImportContactsFromFileDialog() {
  return window['go']['main']['DesktopApp']['ImportContactsFromFileDialog']();
}

export function SelectContactImportFile() {
  return window['go']['main']['DesktopApp']['SelectContactImportFile']();
}
