// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Health():Promise<Record<string, string>>;

export function ImportContactsFromFileDialog():Promise<app.ContactImportResult>;

export function SelectCampaignAttachmentFiles():Promise<Array<string>>;

export function SelectContactImportFile():Promise<string>;
